#!/bin/sh

cd $(dirname $0)

for test in asm-tests/*.fvma
do
	./fvma $test
	outfile=`basename $test .fvma`.fvm
	if ! diff -u tests/$outfile asm-tests/$outfile
	then
		echo
		echo ERROR asm-tests/$outfile is different from tests/$outfile
		echo
	fi
done


